version: "3.8"

services:
  hammond:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hammond_service
    environment:
      CONFIG: /config
      DATA: /assets
      JWT_SECRET: somethingverystrong
    volumes:
      - config_volume:/config
      - assets_volume:/assets
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  config_volume:
    driver: local
  assets_volume:
    driver: local
